#!/bin/sh

printf 'y'| sudo apt install maltego
printf 'y' |sudo apt install msfpc
printf 'y' |sudo apt install set
printf 'y' |sudo apt install faraday 
printf 'y' |sudo apt install recordmydesktop
printf 'y' |sudo apt install pipal
printf 'y' |sudo apt install cutycapt
printf 'y' |sudo apt install hashdeep
printf 'y' |sudo apt install bulk-extractor
printf 'y' |sudo apt install binwalk
printf 'y' |sudo apt install autopsy
printf 'y' |sudo apt install sleuthkit
printf 'y' |sudo apt install pdfid
printf 'y' |sudo apt install pdf-parser
printf 'y' |sudo apt install forensic-artifacts
printf 'y' |sudo apt install guymager
printf 'y' |sudo apt install magicrescue
printf 'y' |sudo apt install scalpel
printf 'y' |sudo apt install scrounge-ntfs
printf 'y' |sudo apt install dbd
printf 'y' |sudo apt install powersploit
printf 'y' |sudo apt install sbd
printf 'y' |sudo apt install dns2tcp
printf 'y' |sudo apt install exe2hexbat
printf 'y' |sudo apt install iodine
printf 'y' |sudo apt install miredo
printf 'y' |sudo apt install proxychains4
printf 'y' |sudo apt install proxytunnel
printf 'y' |sudo apt install ptunnel
printf 'y' |sudo apt install pwnat
printf 'y' |sudo apt install sslh
printf 'y' |sudo apt install stunnel4
printf 'y' |sudo apt install udptunnel
printf 'y' |sudo apt install laudanum
printf 'y' |sudo apt install weevely
printf 'y' |sudo apt install mimikatz
printf 'y' |sudo apt install dnschef
printf 'y' |sudo apt install netsniff-ng
printf 'y' |sudo apt install rebind
printf 'y' |sudo apt install sslsplit
printf 'y' |sudo apt install tcpreplay
printf 'y' |sudo apt install ettercap-graphical
printf 'y' |sudo apt install macchanger
printf 'y' |sudo apt install mitmproxy
printf 'y' |sudo apt install responder
printf 'y' |sudo apt install wireshark
printf 'y' |sudo apt install metasploit-framework
printf 'y' |sudo apt install exploitdb
printf 'y' |sudo apt install sqlmap
printf 'y' |sudo apt install sqlitebrowser
printf 'y' |sudo apt install bully
printf 'y' |sudo apt install fern-wifi-cracker
printf 'y' |sudo apt install spooftooph
printf 'y' |sudo apt install aircrack-ng
printf 'y' |sudo apt install kismet
printf 'y' |sudo apt install pixiewps
printf 'y' |sudo apt install reaver
printf 'y' |sudo apt install wifite
printf 'y' |sudo apt install clang
printf 'y' |sudo apt install nasm
printf 'y' |sudo apt install radare2
printf 'y' |sudo apt install chntpw
printf 'y' |sudo apt install hashcat
printf 'y' |sudo apt install hashid
printf 'y' |sudo apt install hash-identifier
printf 'y' |sudo apt install ophcrack
printf 'y' |sudo apt install ophcrack-cli
printf 'y' |sudo apt install samdump2
printf 'y' |sudo apt install hydra
printf 'y' |sudo apt install hydra-gtk
printf 'y' |sudo apt install onesixtyone
printf 'y' |sudo apt install patator
printf 'y' |sudo apt install thc-pptp-bruter
printf 'y' |sudo apt install passing-the-hash
printf 'y' |sudo apt install mimikatz
printf 'y' |sudo apt install smbmap
printf 'y' |sudo apt install cewl
printf 'y' |sudo apt install crunch
printf 'y' |sudo apt install john
printf 'y' |sudo apt install medusa
printf 'y' |sudo apt install ncrack
printf 'y' |sudo apt install wordlists
printf 'y' |sudo apt install rsmangler
printf 'y' |sudo apt install dnsenum
printf 'y' |sudo apt install dnsrecon
printf 'y' |sudo apt install fierce
printf 'y' |sudo apt install lbd
printf 'y' |sudo apt install wafw00f
printf 'y' |sudo apt install arping
printf 'y' |sudo apt install fping
printf 'y' |sudo apt install hping3
printf 'y' |sudo apt install masscan
printf 'y' |sudo apt install thc-ipv6
printf 'y' |sudo apt install nmap
printf 'y' |sudo apt install theharvester
printf 'y' |sudo apt install netdiscover
printf 'y' |sudo apt install netmask
printf 'y' |sudo apt install enum4linux
printf 'y' |sudo apt install nbtscan
printf 'y' |sudo apt install smbmap
printf 'y' |sudo apt install swaks
printf 'y' |sudo apt install onesixtyone
printf 'y' |sudo apt install snmpcheck
printf 'y' |sudo apt install ssldump
printf 'y' |sudo apt install sslh
printf 'y' |sudo apt install sslscan
printf 'y' |sudo apt install sslyze
printf 'y' |sudo apt install dmitry
printf 'y' |sudo apt install ike-scan
printf 'y' |sudo apt install legion
printf 'y' |sudo apt install recon-ng
printf 'y' |sudo apt install spike
printf 'y' |sudo apt install voiphopper
printf 'y' |sudo apt install legion
printf 'y' |sudo apt install nikto
printf 'y' |sudo apt install nmap
printf 'y' |sudo apt install unix-privesc-check
printf 'y' |sudo apt install wpscan
printf 'y' |sudo apt install burpsuite
printf 'y' |sudo apt install dirb
printf 'y' |sudo apt install dirbuster
printf 'y' |sudo apt install wfuzz
printf 'y' |sudo apt install cadaver
printf 'y' |sudo apt install davtest
printf 'y' |sudo apt install skipfish
printf 'y' |sudo apt install wapiti
printf 'y' |sudo apt install whatweb
printf 'y' |sudo apt install commix
printf 'y' |sudo apt install zaproxy
printf 'y' |sudo apt install freerdp2-x11
printf 'y' |sudo apt install scalpel
printf 'y' |sudo apt install spiderfoot

echo "The script has been successfully executed"
echo "Tools has been added/installed"
echo "Thanks for using this script"
